### ISSUE TITLE
Update dagger version

### ISSUE THREAD

**Issue by dhruvnagarajan** [dhruvnagarajan/Android-Dagger-ContributesAndroidInjector-Example#1]

**Comment by xlDoug** [comment]
What is needed?

**Comment by indracs7** [comment]
@dhruvnagarajan Should I update the whole build.gradle?

**Comment by indracs7** [comment]
Updated the dagger version
PR #2

**Comment by PurpleHorse07** [comment]
@dhruvnagarajan Updated dagger version only in PR #3. Merge it to complete my 4 PRs. :P

**Comment by dhruvnagarajan** [comment]
> What is needed?

@xlDoug repo has to reflect recent changes made to dagger. One of them being replacement of Builder with Factory.
